export const billAndTedWords = [
    'excellent',
    'bogus',
    'most triumphant',
    'totally',
    'dude',
    'party on',
    'be excellent to each other',
    'radical',
    'gnarly',
    'whoa',
    'station',
    'bodacious',
    'heinous',
    'no way',
    'for sure',
    'unreal',
    'time-traveling',
    'Wyld Stallyns',
    'air guitar',
    'awesome',
    'rock on',
    'strange things are afoot',
    'historical babes',
    'rufus',
    'so-crates',
    'waterloo',
    'san dimas high school football rules',
    'non-non-non-heinous',
    'future dudes',
    'wild stallions',
];
