export const bostonianWords = [
    'wicked',
    'pissa',
    'packie',
    'bubbler',
    'dunks',
    'frappe',
    'grinder',
    'jimmies',
    'regular',
    'rotary',
    'spuckie',
    'tonic',
    'bang a uey',
    'kehd',
    'triple decker',
    'hoodsie',
    'parlor',
    'barrel',
    'cellar',
    'package store',
    'common',
    'southie',
    'northshore',
    'dot',
    'townie',
    'statie',
    'mass pike',
    'greenline',
];
