export const corporateWords = [
    'synergy',
    'leverage',
    'strategic',
    'optimization',
    'innovation',
    'disruption',
    'scalable',
    'sustainable',
    'deliverable',
    'milestone',
    'timeline',
    'bandwidth',
    'capacity',
    'resource',
    'scope',
    'stakeholder',
    'touch base',
    'circle back',
    'reach out',
    'ping',
    'sync',
    'alignment',
    'cascade',
    'dialogue',
    'deep dive',
    'drill down',
    'granular',
    'high level',
    'metrics',
    'analytics',
    'insights',
    'data-driven',
    'streamline',
    'optimize',
    'efficient',
    'productive',
    'actionable',
    'implement',
    'execute',
    'facilitate',
    'culture fit',
    'team player',
    'collaborative',
    'dynamic',
    'fast-paced',
    'proactive',
    'ownership',
    'workflow',
    'process',
    'framework',
    'methodology',
    'best practice',
    'standard operating procedure',
    'huddle',
    'standup',
    'all-hands',
    'sync',
    'meeting',
    'conference',
    'workshop',
    'breakout session',
    'benchmark',
    'performance',
    'objective',
    'goal',
    'target',
    'metric',
    'KPI',
    'ROI',
    'bottom line',
];
