export const genZWords = [
    'bestie',
    'slay',
    'periodt',
    'bussin',
    'no cap',
    'fr fr',
    'based',
    'mid',
    'lowkey',
    'highkey',
    'sus',
    'sheesh',
    'vibe',
    'rent free',
    'main character',
    'living rent free',
    'understood the assignment',
    'tea',
    'slaps',
    'hits different',
    'fam',
    'goat',
    'bet',
    'bruh',
    'deadass',
    'fire',
    'facts',
    'ion',
    'ngl',
];
