export const hobbitWords = [
    'shire',
    'hobbiton',
    'bag end',
    'second breakfast',
    'elevenses',
    'afternoon tea',
    'supper',
    'ale',
    'pipe-weed',
    'merry',
    'jolly',
    'burrow',
    'muck',
    'cozy',
    'feast',
    'adventure',
    'ring',
    'precious',
    'frodo',
    'samwise',
    'bilbo',
    'gandalf',
    'middle-earth',
    'shirefolk',
    'tookish',
    'comfort',
    'firelight',
    'riddle',
    'larder',
    'pantry',
    'garden',
    'potatoes',
    'barley',
    'biscuit',
    'walking stick',
    'bree',
    'green dragon',
    'wizard',
    'wanderlust',
    'hill',
    'quiet',
    'friendship',
    'peaceful',
];
