export const scoobyDooWords = [
    'ruh-roh',
    'zoinks',
    'jinkies',
    'jeepers',
    'raggy',
    'like',
    'man',
    'groovy',
    'far out',
    'scooby snacks',
    'sandwich',
    'trap',
    'clue',
    'spooky',
    'haunted',
    'phantom',
    'ghoul',
    'mystery machine',
    'danger-prone',
    'ruh-uh',
    'reeheehee',
];
