export const surferWords = [
    'aloha',
    'barrel',
    'beach break',
    'brah',
    'carve',
    'chill',
    'dawn patrol',
    'dude',
    'epic',
    'floater',
    'gnarly',
    'goofy foot',
    'hang loose',
    'hang ten',
    'killer',
    'lineup',
    'lip',
    'localism',
    'noice',
    'offshore',
    'over the falls',
    'pipeline',
    'rad',
    'reef break',
    'ride the nose',
    'rip curl',
    'sesh',
    'shaka',
    'shred',
    'sick',
    'slotted',
    'stoked',
    'surfs up',
    'totally',
    'tubular',
    'waves',
    'wipeout',
];
