export const valleyWords = [
    'as if',
    'awesome',
    'bag your face',
    'barf me out',
    'big time',
    'bogus',
    'borked',
    'chill',
    'duh',
    'fer sure',
    'for real',
    'gag me',
    'gag me with a spoon',
    'geez',
    'gnarly',
    'gross',
    'grody',
    'gross me out',
    'hella',
    'like',
    'major',
    'mondo',
    'no way',
    'oh my gosh',
    'oh my god',
    'radical',
    'really',
    'righteous',
    'so',
    'totes',
    'totes awesome',
    'totally',
    'tubular',
    'um',
    'whatever',
    'what-everrr',
];
