export const yodaWords = [
    'hmm',
    'yes',
    'no',
    'hmmm',
    'do',
    'do not',
    'there is no try',
    'force',
    'Jedi',
    'Padawan',
    'dark side',
    'light side',
    'Master',
    'apprentice',
    'learn',
    'unlearn',
    'balance',
    'destiny',
    'fear',
    'anger',
    'hate',
    'suffering',
    'patience',
    'meditate',
    'wisdom',
    'powerful',
    'ally',
    'around the survivors, a perimeter create',
    'warrior',
    'luminous beings',
    'crude matter',
    'galaxy',
    'mind what you have learned',
    'future',
    'past',
    'adventure',
    'excitement',
    'calm',
    'flow',
    'train',
    'one with the Force',
    'always in motion is the future',
];
